#!/bin/bash

echo "🚀 Deploying Fortune Investment Platform to Production..."

echo "📋 Production Configuration:"
echo "- Tiered investment plans (Bronze to Gold)"
echo "- M-PESA production credentials"
echo "- Automatic callback processing"
echo "- Authentication restored"

echo ""
echo "📤 Deployment Commands:"
echo ""
echo "1. Backend Deployment:"
echo "   cd backend"
echo "   git add ."
echo "   git commit -m 'Production ready: Auth, M-PESA, tiered plans'"
echo "   git push origin main"
echo ""
echo "2. Frontend Deployment:"
echo "   cd frontend"
echo "   git add ."
echo "   git commit -m 'Production ready: API URLs and authentication'"
echo "   git push origin main"
echo ""
echo "3. Update Render Environment Variables:"
echo "   MPESA_CONSUMER_KEY=yqApGHNGuRmG2y94AXbUHukXqmEIwsAFaWcIGPejedWNcMUH"
echo "   MPESA_CONSUMER_SECRET=RUCumMcAa73DXEtddIYZfhHAAtlxJ2stPkmjfAhSfSa0mvYq7VH2JdBl8cwMtDTo"
echo "   MPESA_SHORTCODE=4185659"
echo "   MPESA_CALLBACK_URL=https://fortune-platform-1.onrender.com/api/payments/callback"
echo "   MPESA_ENV=production"
echo ""
echo "✅ After deployment, M-PESA callbacks will work automatically!"
echo "🎯 Test with Bronze plan (KSh 1) for immediate results"