-- Fix database permissions
GRANT ALL PRIVILEGES ON DATABASE fortune_db TO fortune;
GRANT ALL PRIVILEGES ON SCHEMA public TO fortune;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fortune;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fortune;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fortune;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO fortune;